#!/usr/bin/bash
./update.py -lde M14 "Magic 2014 Core Set"
./update.py -lde THS "Theros"
./update.py -lde BNG "Born of the Gods"
./update.py -lde JOU "Journey into Nyx"
./update.py -lde M15 "Magic 2015 Core Set"
./update.py -lde KTK "Khans of Tarkir"
./update.py -lde FRF "Fate Reforged"
./update.py -lde DTK "Dragons of Tarkir"
./update.py -lde ORI "Magic Origins"
./update.py -lde BFZ "Battle for Zendikar"
./update.py -lde OGW "Oath of the Gatewatch"
./update.py -lde SOI "Shadows over Innistrad"
